import { useEffect, useState, type ReactNode } from 'react';
import { Link, Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { FolderPlus, LogOut, Plus, ShieldCheck } from 'lucide-react';
import type { DataRoomSummary, FolderContents } from '@acme/contracts';
import { api } from './lib/api';
import { supabase } from './lib/supabase';
import { CreateFolderDialog } from './components/CreateFolderDialog';
import { EmptyState } from './components/EmptyState';
import { RoomContents } from './components/RoomContents';

function Login() {
  const [error, setError] = useState('');
  const signIn = async () => { if (!supabase) return setError('Add Supabase credentials to apps/web/.env before signing in.'); const { error: authError } = await supabase.auth.signInWithOAuth({ provider: 'google', options: { redirectTo: window.location.origin } }); if (authError) setError(authError.message); };
  return <main className="grid min-h-screen place-items-center p-6"><section className="w-full max-w-md rounded-2xl border bg-white p-8 shadow-card"><div className="mb-8 flex items-center gap-3"><div className="rounded-xl bg-brand p-2 text-white"><ShieldCheck size={22} /></div><span className="font-semibold">Acme Data Room</span></div><h1 className="text-2xl font-semibold tracking-tight">Due diligence, organized.</h1><p className="mt-3 text-sm leading-6 text-slate-500">Securely collect, organize, and share the documents your deal team needs.</p><button onClick={signIn} className="mt-8 flex w-full items-center justify-center gap-3 rounded-lg border bg-white py-2.5 text-sm font-medium shadow-sm hover:bg-slate-50"><span className="font-bold text-blue-500">G</span> Continue with Google</button>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<p className="mt-7 text-center text-xs text-slate-400">Read-only sharing keeps your sensitive materials controlled.</p></section></main>;
}

function Dashboard() {
  const [rooms, setRooms] = useState<DataRoomSummary[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { api.rooms().then(setRooms).catch((cause) => setError(cause.message)).finally(() => setLoading(false)); }, []);
  const createRoom = async () => { const name = window.prompt('Name your Data Room'); if (!name?.trim()) return; try { const room = await api.createRoom(name.trim()); setRooms((current) => [room, ...current]); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to create room.'); } };
  return <Layout><div className="mb-8 flex items-end justify-between"><div><p className="text-sm font-medium text-brand">Workspace</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Your Data Rooms</h1></div><button onClick={createRoom} className="rounded-lg bg-brand px-3.5 py-2 text-sm font-medium text-white"><Plus className="mr-1.5 inline" size={17} />New Data Room</button></div>{error && <p className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{loading ? <p className="text-sm text-slate-500">Loading your rooms…</p> : rooms.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{rooms.map((room) => <Link key={room.id} to={`/rooms/${room.id}`} className="rounded-xl border bg-white p-5 shadow-card transition hover:-translate-y-0.5 hover:border-blue-200"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-blue-50 text-brand"><ShieldCheck size={20} /></div><h2 className="mt-5 font-semibold">{room.name}</h2><p className="mt-1 line-clamp-2 min-h-10 text-sm text-slate-500">{room.description ?? 'No description provided.'}</p><p className="mt-5 text-xs text-slate-400">Updated {new Date(room.updatedAt).toLocaleDateString()}</p></Link>)}</div> : <div className="rounded-xl border border-dashed bg-white py-20 text-center"><h2 className="font-semibold">Create your first Data Room</h2><p className="mt-2 text-sm text-slate-500">Start with one secure place for all deal documents.</p></div>}</Layout>;
}

function RoomPage() {
  const { roomId } = useParams(); const navigate = useNavigate(); const [folderId, setFolderId] = useState<string | undefined>(); const [contents, setContents] = useState<FolderContents | null>(null); const [error, setError] = useState(''); const [dialogOpen, setDialogOpen] = useState(false);
  const load = () => { if (roomId) api.contents(roomId, folderId).then(setContents).catch((cause) => setError(cause.message)); };
  useEffect(load, [roomId, folderId]);
  if (!roomId) return <Navigate to="/" replace />;
  const createFolder = async (name: string) => { await api.createFolder(roomId, name, folderId); load(); };
  return <Layout><button onClick={() => navigate('/')} className="mb-5 text-sm text-slate-500 hover:text-ink">← All Data Rooms</button><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><nav className="mb-2 flex items-center gap-1 text-sm text-slate-500"><button onClick={() => setFolderId(undefined)} className="hover:text-brand">Data Room</button>{contents?.breadcrumbs.map((crumb) => <span key={crumb.id} className="flex items-center gap-1">/ <button onClick={() => setFolderId(crumb.id)} className="hover:text-brand">{crumb.name}</button></span>)}</nav><h1 className="text-2xl font-semibold tracking-tight">{contents?.folder?.name ?? 'Data Room'}</h1></div><button onClick={() => setDialogOpen(true)} className="rounded-lg border bg-white px-3 py-2 text-sm font-medium"><FolderPlus className="mr-1.5 inline" size={16} />New folder</button></div>{error ? <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p> : contents?.items.length ? <RoomContents items={contents.items} onOpenFolder={setFolderId} /> : <EmptyState onNewFolder={() => setDialogOpen(true)} />}<CreateFolderDialog open={dialogOpen} onClose={() => setDialogOpen(false)} onSubmit={createFolder} /></Layout>;
}

function Layout({ children }: { children: ReactNode }) { return <><header className="border-b bg-white"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5"><Link to="/" className="flex items-center gap-2 font-semibold"><span className="rounded-lg bg-brand p-1.5 text-white"><ShieldCheck size={17} /></span>Acme Data Room</Link><button onClick={() => void supabase?.auth.signOut()} className="text-sm text-slate-500 hover:text-ink"><LogOut className="mr-1 inline" size={16} />Sign out</button></div></header><main className="mx-auto max-w-7xl px-5 py-10">{children}</main></> }

export default function App() { const [authenticated, setAuthenticated] = useState(false); const [ready, setReady] = useState(!supabase); useEffect(() => { if (!supabase) return; supabase.auth.getSession().then(({ data }) => { setAuthenticated(Boolean(data.session)); setReady(true); }); const { data } = supabase.auth.onAuthStateChange((_event, session) => setAuthenticated(Boolean(session))); return () => data.subscription.unsubscribe(); }, []); if (!ready) return null; if (!supabase) return <Login />; return authenticated ? <Routes><Route path="/" element={<Dashboard />} /><Route path="/rooms/:roomId" element={<RoomPage />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes> : <Login />; }
